# Generated by Django 5.1 on 2024-09-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('qty', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('sub_category', models.CharField(max_length=50, verbose_name='sub_category')),
                ('recordedAt', models.DateTimeField(auto_now_add=True, verbose_name='recordedAt')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('qty_in_stock', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Item')),
            ],
        ),
    ]
