# Generated by Django 5.1 on 2024-09-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qty',
        ),
    ]
