# Generated by Django 5.1 on 2024-09-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Item Slug'),
        ),
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Stock Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Category Slug'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU'),
        ),
    ]
