# Generated by Django 5.1.1 on 2024-10-02 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_alter_item_price_alter_stock_qty_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Item'),
        ),
    ]
