# Generated by Django 5.1 on 2024-09-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Category Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Category Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Item Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Stock Slug'),
            preserve_default=False,
        ),
    ]
