# Generated by Django 5.1 on 2024-09-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Category Slug'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Item Slug'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='Stock Slug'),
        ),
    ]
